# Пользователи
## Создание нового пользователя

POST http://localhost:5000/users/registration HTTP/1.1
Content-Type: application/json

{
  "name": "Star",
  "email": "keks@mail.ru",
  "password": "123456",
  "userType":"pro"
}

###

## Создание нового пользователя неправильный тип файла

POST http://localhost:5000/users/registration HTTP/1.1
Content-Type: application/json

{
  "name": "Star",
  "email": "keks1@mail.ru",
  "password": "123456",
  "avatar": "bad.svg",
  "userType":"pro"
}

###

## Вход в закрытую часть

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks1@mail.ru",
  "password": "123456"
}

###

## Проверка состояния пользователя

GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3MxQG1haWwucnUiLCJuYW1lIjoiU3RhciIsImlkIjoiNjVkZGRmMTIwNWMzOTRmODFjMzc5NTQ4IiwiaWF0IjoxNzA5MjE0OTM5LCJleHAiOjE3MDkzODc3Mzl9._jVLD3HnGeGbL9dc3CIn2NabFCaj2hy8N1R6fmdODl8


###

## Отправить изображение

POST http://localhost:5000/users/65db3ef34a5c8c8b4e0df3fd/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="octopus-64x64.png"
Content-Type: image/jpg

< D:/avatar1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
