@host = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3Npa0BtYWlsLnJ1IiwibmFtZSI6IlN0YXIiLCJpZCI6IjY1ZTMwMzI2ZWE0OWFkNmZhM2ZlZDUwNSIsImlhdCI6MTcwOTkwNDQ0MiwiZXhwIjoxNzEwMDc3MjQyfQ.F6vdwYXvEp9Vx0F9gd9yhIUDjBEg7UFyJAbO7M9YQ6k

# Предложения по аренде

## Список предложений по аренде

GET {{ host }}/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}

###

## Список предложений по аренде по городу

GET {{ host }}/offers/?city=Paris HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}
###

## Создание нового предложения

POST {{ host }}/offers/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "title": "Wood, wood...",
  "description": "Комплекс апартаментов",
  "city": "Paris",
  "image": "photo6.jpg",
  "photos": [
    "photo7.jpg",
    "photo8.jpg",
    "photo9.jpg",
    "photo10.jpg",
    "photo11.jpg",
    "photo12.jpg"
  ],
  "isPremium": true,
  "typeOfHousing": "apartment",
  "roomsCount": 2,
  "guestsCount": 1,
  "price": 524,
  "comforts": [
    "Washer",
    "Towels"
  ],
  "offerLocation": {
        "latitude": 53.551024,
        "longitude": 9.920481
    }
}

###

## Детальная информация по предложению

GET  {{ host }}/offers/65d83da4d91892a628b5ccb7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}

###

## Удаление предложения

DELETE  {{ host }}/offers/65e416e61fee5b5e6b102e6a/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}

###

## Редактирование предложения

PATCH  {{ host }}/offers/65e416e61fee5b5e6b102e6a/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "title": "Apartment for you"
}

###

##Премиум по городу
GET {{ host }}/offers/Paris/premium HTTP/1.1
Authorization: Bearer {{ token }}

###

## Добавление и удаление предложения в/из избранного проверить

PUT  {{ host }}/offers/65eacad8ee31b1805d65436d/favorite/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "isFavorite": true
}

###

## Получить избранные предложения пользователя

GET  {{ host }}/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{ token }}
